name: Test

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
        
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    
    - name: Run Tests      
      run: dotnet test        